services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: kanban
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - kanban-application
    restart: unless-stopped
#  application:
#    container_name: application
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    environment:
#      - APP_DATASOURCE_MAIN_JDBC-URL=jdbc:postgresql://postgres:5432/kanban
#    ports:
#      - "8080:8080"
#    networks:
#      - kanban-application
#    depends_on:
#      - "postgres"
#    volumes:
#      - ./:/app


networks:
  kanban-application:
    name: kanban-application
    driver: bridge

volumes:
  postgres: